@startuml Fig31
title Figura 3.1 - Exemplo de Atores
:Gerente:
:Funcionário: as Man2
actor Cliente
actor :Caixa Eletrônico: as System1
actor :Sistema de Contas a Receber: as System2
@enduml

@startuml Fig32
title Figura 3.2 - Exemplo de Caso de Uso
(Abertura de Conta)
@enduml


@startuml Fig33
title Figura 3.3 - Associação entre um anor e um caso de Uso
:Cliente: -- (Abertura de Conta)
@enduml

@startuml Fig34
title Figura 3.4 - Especialização / Generalização
(Abertura de Conta) <|-- (Abertura de Conta Especial)
(Abertura de Conta) <|-- (Abertura de Conta Poupança)
@enduml

@startuml Fig35
title Figura 3.5 - Especialização / Generalização com Atores
:Pessoa: <|-- :Pessoa Física:
:Pessoa: <|-- :Pessoa Juridica:
@enduml

@startuml Fig36
left to right direction
title Figura 3.6 - Inclusão
actor Cliente 
actor Banco #blue
usecase Saque as S
usecase Deposito as D
usecase "Registrar Movimento" as RM
Cliente -- S
Cliente -- D
Banco -left- S #blue
Banco -left- D #blue
(D) .> (RM) : <<include>>
(S) .> (RM) : <<include:>>
@enduml

@startuml Fig37
left to right direction
title Figura 3.7 - Extensão
actor Cliente 
actor Funcionario #blue
usecase "Encerrar Conta" as EC
usecase Deposito as D
usecase Saque as S
Cliente -- (EC)
Funcionario -- (EC)
(S) .> (EC) : <<Extend>>
(D) .> (EC) : <<Extend>>

@enduml


@startuml Fig38
left to right direction
title Figura 3.8 - Diagrama de Caso de Uso de um Sistema de Venda de Apólices de Seguros
/'Bloco de Atores'/
actor Cliente
actor Vistoriador
actor Secretária
actor Corretor
actor "Contas a Pagar e receber" as CPR
actor Matriz
/'---------------------------'/
/'Casos de Uso'/
usecase "Manter Clientes" as MC
usecase "Manter Veículos" as MV
usecase "Gerar Apólice" as GA
usecase "Quitar Parcela" as QP
usecase "Manter Sinistro" as MS
usecase "Verifica Veículos" as VV
usecase "Verifica Valor Seguro" as VVS
usecase "Manter Parcelas a Receber" as MPaR
/'---------------------------'/
Cliente --> MC : Informações pessoais
Cliente --> MV : Inf. Veiculo
Cliente -- GA : Inf. Op. Parcelas
Cliente -- QP
Cliente --> MS
MC -- Corretor
MV -- Corretor
GA -- Corretor : Inf. Apólice
Corretor <- VV
Corretor -- VVS
VV -- Vistoriador
VVS -- Matriz
GA -.> MPaR : <<Include>>
QP -.> MPaR : <<Include>>
MPaR -- CPR
QP -- Secretária
MS -- Secretária
MS <-- Vistoriador

@enduml

@startuml Fig39
left to right direction
title Figura 3.9 - Diagrama de Casos de Uso de um sistema Bancário

/'Bloco Atores'/
actor Cliente
actor Funcionário
actor Banco
/'----------------'/
/'Casos de Uso'/
usecase "Abertura Conta Comum" as ACC
usecase "Abertura Conta Especial" as ACE
usecase "Abertura Conta Poupança" as ACP
usecase "Manter Cliente" as MC
usecase "Encerrar Conta" as EC
usecase Saldo
usecase Deposito
usecase Saque
usecase Extrato
usecase "Registrar Movimento" as RM
/'----------------------------'/

(ACE) --|> (ACC)
(ACP) --|> (ACC)
(ACC) -- Funcionário
(MC) -- Funcionário
(ACC) <.- (MC) : <<Extend>>
(EC) <.- (MC) : <<Extend>>
Cliente -- (EC)
Cliente -- ACC : Inf. Pessoais
Cliente -- (Saldo)
Cliente -- (Deposito)
Cliente -- (Saque)
Cliente -- (Extrato)
(EC) -- Banco
Saldo -- Banco
Deposito -- Banco
Saque -- Banco
Extrato -- Banco
(Deposito) -.> (RM) : <<Include>>
(Saque) -.> (RM) : <<Include>>
(EC) <.- (Deposito) : <<Extend>>
(EC) <.- (Saque) : <<Extend>>
(Saldo) <.- (EC) : <<Include>>
@enduml

@startuml Fig310
left to right direction
title Figura 3.10 - Exemplo de Notas
note "Isso é um nota" as N1
N1 -. (Abertura de Conta)
@enduml

@startuml Fig311
left to right direction
title Figura 3.11 - Exemplo de Pacotes
package SCaP as "Sistema de Contas a Pagar" 
package SS as  "Sistema de Seguradora"

SCaP -.> SS
@enduml 

@startuml Fig312
left to right direction
title Figura 3.12 - Estereótipo de Rótulo
usecase "Abertura de Contas" as AC <<process>>
@enduml


@startuml Fig313
left to right direction
title Figura 3.13 - Estereótipo de Gráfico
boundary "Caixa Eletrônico"
@enduml